 **基本的な線形代数**
 
 Juliaの基本構文はその他の言語と似ているがいくつかの重要な違いがあります．

In [1]:
A = rand(1:4, 3,3)

3×3 Array{Int64,2}:
 4  1  2
 3  1  4
 4  1  3

In [3]:
B = A
C =copy(A)
[ B C]

3×6 Array{Int64,2}:
 4  1  2  4  1  2
 3  1  4  3  1  4
 4  1  3  4  1  3

In [6]:
# 注意！
A[1] = 17
[B 　C　] #　BとAは同じメモリを使っているのでAかBのどちらかを変更するともう一方に影響を与えます．

3×6 Array{Int64,2}:
 17  1  2  4  1  2
  3  1  4  3  1  4
  4  1  3  4  1  3

そして単位ベクトルについても見てみましょう

In [7]:
x = ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

気づいて欲しいのですが，$A$はArray{Float64,2}であるが，$x$はArray{Float64,1}という状態です．JuliaではVector{Type}=Array{Type,1}， Matrix{Type}=Array{Type,2}というエイリアスとして定義されている．

In [8]:
b = A*x

3-element Array{Float64,1}:
 20.0
  8.0
  8.0