**繰り返し文**

Juliaでの繰り返し文は```for```と```while```が使えます

**while文**

```while```は以下のように使います．

```while *条件*
            *処理内容*
     end```
     
```while```はカウントしたり，アレイの中で繰り返すのに使ったりします

In [1]:
n = 0;
while n < 10
    n += 1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [2]:
myfriends = ["Ted", "Lisa", "Lewis", "Max", "Chales"]

i = 1
while i <= length(myfriends)
    friend = myfriends[i]
    println("Hi $friend, it's great to see you!")
    i += 1
end

Hi Ted, it's great to see you!
Hi Lisa, it's great to see you!
Hi Lewis, it's great to see you!
Hi Max, it's great to see you!
Hi Chales, it's great to see you!


**for文**

```for```は以下のように使います

```for *変数*　in *反復可能な範囲*
        *処理内容*
     end```

In [3]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [7]:
myfriends = ["Ted", "Lisa", "Lewis", "Max", "Chales"]

for friend in myfriends
    println("Hi $friend, it's great to see you!")
end

Hi Ted, it's great to see you!
Hi Lisa, it's great to see you!
Hi Lewis, it's great to see you!
Hi Max, it's great to see you!
Hi Chales, it's great to see you!


ここで```in```は```=``` や```∈```に置き換えることも可能です

In [8]:
for n = 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [9]:
for n ∈ 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


```for```文には追加のテーブルを作ることができ，行と列の和をそれぞれの入力にすることができます．

はじめにゼロ行列を使ってみましょう

In [13]:
m, n = 5, 5
A = zeros(m, n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [14]:
for i in 1:m
    for j in 1:n
        A[i, j] = i + j
    end
end
A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

また，```for```文に関してはネスト構造をとることができます．

In [15]:
B = zeros(m, n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [16]:
for i in 1:m, j in 1:n
    B[i, j] = i + j
end
B

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

しかしJuliaではもっとクリエイティブな*包括的アレイ*を使うことができます

In [17]:
C = [i + j for i in 1:m, j in 1:n]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

次の例では```for```の中で包括的アレイを拡張して，どんどんサイズが大きくなる行列を作ってみます．

In [18]:
for n in 1:10
    A = [i + j for i in 1:n, j in 1:n]
    display(A)
end

1×1 Array{Int64,2}:
 2

2×2 Array{Int64,2}:
 2  3
 3  4

3×3 Array{Int64,2}:
 2  3  4
 3  4  5
 4  5  6

4×4 Array{Int64,2}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Array{Int64,2}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Array{Int64,2}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Array{Int64,2}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

9×9 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10
  3   4   5   6   7   8   9  10  11
  4   5   6   7   8   9  10  11  12
  5   6   7   8   9  10  11  12  13
  6   7   8   9  10  11  12  13  14
  7   8   9  10  11  12  13  14  15
  8   9  10  11  12  13  14  15  16
  9  10  11  12  13  14  15  16  17
 10  11  12  13  14  15  16  17  18

10×10 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10  11
  3   4   5   6   7   8   9  10  11  12
  4   5   6   7   8   9  10  11  12  13
  5   6   7   8   9  10  11  12  13  14
  6   7   8   9  10  11  12  13  14  15
  7   8   9  10  11  12  13  14  15  16
  8   9  10  11  12  13  14  15  16  17
  9  10  11  12  13  14  15  16  17  18
 10  11  12  13  14  15  16  17  18  19
 11  12  13  14  15  16  17  18  19  20